# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rustbucket_wrappers", use_symbols = TRUE, package_name = "rustbucket")

#' @docType package
#' @usage NULL
#' @useDynLib rustbucket, .registration = TRUE
NULL

#' Compute the Hamming distance between a sequence and a vector of sequences with a limit. Complexity: O(n).
#' @export
hamming <- function(alpha, beta, limit, num_threads) .Call(wrap__hamming, alpha, beta, limit, num_threads)


# nolint end
